# Generated by Django 5.2.8 on 2025-12-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignment',
            table='assignment',
        ),
        migrations.AlterModelTable(
            name='assignmentsubmission',
            table='assignment_submission',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quiz',
        ),
        migrations.AlterModelTable(
            name='quizsubmission',
            table='quiz_submission',
        ),
    ]
