# Generated by Django 6.0.2 on 2026-03-07 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_quiz_status'),
        ('lectures', '0007_lecture_context_lecture_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='generating', max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lecture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lectures.lecture'),
        ),
    ]
