# Generated by Django 6.0 on 2026-03-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_assignment_assignment_data_assignment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed'), ('published', 'Published'), ('archived', 'Archived'), ('draft', 'Draft')], default='generating', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed'), ('published', 'Published'), ('archived', 'Archived'), ('draft', 'Draft')], default='generating', max_length=100),
        ),
    ]
