# Generated by Django 6.0 on 2026-03-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_alter_assignment_status_alter_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
