# Generated by Django 6.0 on 2026-03-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_alter_assignment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
