# Generated by Django 6.0.2 on 2026-03-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_alter_assignmentsubmission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_overridden',
            field=models.BooleanField(default=False),
        ),
    ]
