# Generated by Django 6.0.2 on 2026-03-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_assignmentsubmission_is_graded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='is_graded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='is_overridden',
            field=models.BooleanField(default=False),
        ),
    ]
