# Generated by Django 6.0.2 on 2026-03-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_quizsubmission_is_graded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='answers_data',
            field=models.JSONField(default=list),
        ),
    ]
