# Generated by Django 6.0.2 on 2026-05-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0015_quiz_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_plagiarized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='plagiarism_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
