# Generated by Django 6.0.2 on 2026-05-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_quizviolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
