# Generated by Django 6.0.2 on 2026-05-17 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_quizsubmission_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizviolation',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizviolation',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violation_sub', to='assessment.quizsubmission'),
        ),
    ]
