# Generated by Django 6.0.2 on 2026-05-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0018_quizviolation_reason_quizviolation_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='termination_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
