# Generated by Django 6.0.2 on 2026-05-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_assignmentsubmission_is_plagiarized_and_more'),
        ('assessment', '0019_quizsubmission_termination_reason'),
    ]

    operations = [
    ]
