# Generated by Django 5.2.8 on 2025-12-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_message',
        ),
    ]
