# Generated by Django 6.0.2 on 2026-03-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0003_alter_chatmessage_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
