print("--- LECTURES TASKS MODULE LOADED ---")

from smartlearn_project import celery_app
# ⚠️ Ensure you import all necessary models here!
from .models import ContentSource, Lecture, Course 
import logging

logger = logging.getLogger(__name__)

@celery_app.task
def generate_lecture_from_source(content_source_id):
    """
    Long-running task to process raw content, generate the lecture script, 
    and then trigger video generation via external APIs.
    """
    
    # We retrieve the data as a dictionary to prevent ORM-level crashes on corrupted fields.
    source_data = None
    
    try:
        # 1. Retrieve the ContentSource data as a dictionary (safer than object)
        source_data = ContentSource.objects.filter(id=content_source_id).values(
            'id', 'course_id', 'raw_file', 'ai_prompt', 'uploaded_by_id'
        ).first()

        if not source_data:
            raise ContentSource.DoesNotExist(f"No ContentSource found for ID {content_source_id}")

        # 2. SAFELY RESOLVE THE COURSE TITLE using the raw ID
        course_pk = source_data.get('course_id')
        course_title = "[Course Not Linked/Found]"
        
        if course_pk:
            try:
                # Manually fetch the Course title
                course_title = Course.objects.only('title').get(pk=course_pk).title
            except Course.DoesNotExist:
                course_title = "[Course Not Found]"


        # 3. Use the safe variable in logging
        logger.info(f"Processing content source ID: {content_source_id} for course: {course_title}")
        
        # 4. Now, the debug prints MUST run!
        file_path_db = source_data.get('raw_file')
        file_name = file_path_db if file_path_db else "[No File Uploaded]"
        
        print(f"--- DEBUG: ID from DB: {source_data['id']}")
        print(f"--- DEBUG: Course Title: {course_title}")
        print(f"--- DEBUG: Raw file path from DB: {file_name}")
        
        # --- STEP 1: Process Raw Content and Generate Script (External API Call) ---
        
        # Simulating external AI service call
        generated_script = (
            f"SCRIPT: Lecture content generated by AI using prompt: '{source_data.get('ai_prompt')}' "
            f"and data from {file_name}. (Simulated wait: 15 seconds)"
        )
        
        # --- STEP 2: Generate Video and Transcript (External API Call) ---
        
        # Simulating external video API call
        video_url = "https://external.video.service/lecture_" + str(content_source_id)
        
        # --- STEP 3: Create the final Lecture object and update the DB ---
        
        # We need the actual ContentSource instance for the ForeignKey, 
        # so we fetch it again, only now that we know the basic fields are safe.
        # If the task succeeds up to this point, this final ORM retrieval should be safe.
        source_instance = ContentSource.objects.get(id=content_source_id)

        Lecture.objects.create(
            content_source=source_instance, # Use the re-fetched instance
            topic=f"Auto-Generated Lecture: {course_title} Part {source_data['id']}", 
            summary_text=generated_script, 
            video_url=video_url,
            # Use the raw ID, we assume the user exists
            generated_by_id=source_data.get('uploaded_by_id'), 
            validation_status='pending'
        )
        
        logger.info(f"Successfully created Lecture for source ID: {content_source_id}. Video URL: {video_url}")
        
    except ContentSource.DoesNotExist:
        logger.error(f"ContentSource with ID {content_source_id} not found.")
        
    except Exception as e:
        # Log the full traceback for better error diagnostics
        logger.exception(f"FATAL ERROR during lecture generation for ID {content_source_id}: {e}")
        
    return None