"""
Django settings for smartlearn_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os 
from pathlib import Path
from urllib.parse import parse_qsl, urlparse
import cloudinary # type:ignore
import cloudinary.uploader # type:ignore
import cloudinary.api # type:ignore

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'users.User'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.environ.get("SECRET_KEY")
SECRET_KEY = 'django-insecure-b#l*+n)$8c%e&$wk9qlr=(6s$k7n_+!cch4y^l7b8cx!$oddro'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG")
ALLOWED_HOSTS = []
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Application definition

INSTALLED_APPS = [
    #### for notifications (channels)####
    'daphne',
    'channels',
    #### django defaults #####
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #### my apps ####
    'users',
    'lectures',
    'assessment',
    'ai_core',
    'notifications',
    'dashboard',
    'chatbot',
    #### Packages/Libraries ####
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_celery_beat',
    ### django helpers ###
    'django_extensions',
    'silk',
]

ASGI_APPLICATION = 'smartlearn_project.asgi.application'

CHANNEL_LAYERS = {
    "default":{
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG":{
            "hosts": [("redis",6379)]
        }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'silk.middleware.SilkyMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

# CORS_ALLOWED_ORIGINS = [
#     "https://example.com",
#     "https://sub.example.com",
#     "http://localhost:8080",
#     "http://127.0.0.1:9000",
# ]

CORS_ALLOW_ALL_ORIGINS = True


ROOT_URLCONF = 'smartlearn_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartlearn_project.wsgi.application'


# Celery Beat Settings
CELERY_BEAT_SCHEDULE = {
    'check-deadlines-every-hour': {
        'task': 'notifications.tasks.check_deadline_reminders',
        'schedule': 3600.0, # Runs every hour (3600 seconds)
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ########### moved to neon Db --temporary
# tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': tmpPostgres.path.replace('/', ''),
#         'USER': tmpPostgres.username,
#         'PASSWORD': tmpPostgres.password,
#         'HOST': tmpPostgres.hostname,
#         'PORT': 5432,
#         'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
#     }
# }
############



######
##    CURRENTLY DO NOT USE THIS SETUP  
##    REASON ==> CRASHES THE CELERY WORKER -DOES NOT ALLOW CELERY WORKER TO CONNECT WITH DATABASE 
######
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get("DB_NAME"),  
        'USER': os.environ.get("DB_USER"),  
        'PASSWORD': os.environ.get("DB_PASS"), 
        'PORT':os.environ.get("DB_PORT"),
        'HOST':os.environ.get("DB_HOST"),
    }
}


# ######
# ##    TEMPORARY WORKAROUND 
# ##    ONLY USE IN DEV ENVIORNMENT 
# ##    NOTE* DO NOT PUSH API KEYS EVER 🙏
# ######

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': "smartlearn",  
#         'USER': "smartlearn_user",  
#         'PASSWORD': "celerypass", 
#         'PORT': "3306",
#         'HOST':"127.0.0.1",        
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ----------------------- CELERY CONFIGURATION ----------------------
#--------------------------------------------------------------------
# Broker: The service Celery uses to send and receive tasks (using Redis on localhost default port)

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER")
# Backend: Where Celery stores the task results (also using Redis)
CELERY_RESULT_BACKEND = os.environ.get("CELERY_BROKER")

# Content Type: Defines how task messages are serialized
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Time zone setup
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = 'Asia/Karachi' # Set to your local timezone (e.g., 'Asia/Karachi' or 'UTC')


#######
##     AI API SERVICE RELATED SETTINGS
######

# GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')

## FKN IDIOT DO NOT LEAK THIS AGAIN !!!!!!!!!!
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
# Use a similar method for other keys (e.g., VIDEO_GEN_KEY)



# ----------------------- CLOUDINARY CONFIGURATION ----------------------
#--------------------------------------------------------------------

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get("CLOUD_NAME"),
    'API_KEY': os.environ.get("CLOUDINARY_API_KEY"),
    'API_SECRET': os.environ.get("CLOUDINARY_API_SECRET")
}

cloudinary.config(
    cloud_name = CLOUDINARY_STORAGE['CLOUD_NAME'],
    api_key = CLOUDINARY_STORAGE['API_KEY'],
    api_secret = CLOUDINARY_STORAGE['API_SECRET'],
    secure = True
)


# ----------------------- HEYGEN VIDEO API CONFIGURATION ----------------------
#--------------------------------------------------------------------

HEYGEN_API_KEY = os.environ.get("HEYGEN_API_KEY")


# ----------------------- D-ID VIDEO API CONFIGURATION ----------------------
#--------------------------------------------------------------------
DID_API_KEY = os.environ.get("DID_API_KEY")
