import type { LectureDetails } from "@/types/Lectures/Types";
import styles from "./LectureReviewPage.module.css";
import { useParams, useNavigate } from "react-router-dom";
import { useEffect, useState } from "react";
import apiClient from "@/api/apiClient";
import ValidationActionPanel from "@/components/Dashboard/teacher/ValidationActionPanel";
import { 
  Video, FileText, Info, ArrowLeft, Clock, 
  CheckCircle, Bot, MessageSquare, Trash2 
} from "lucide-react";

const LectureReviewPage = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const lectureId = id;
  const [lecture, setlecture] = useState<LectureDetails | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

  useEffect(() => {
    if (!lectureId) return;
    const fetchLectureDetails = async () => {
      try {
        const response = await apiClient.get(`/lectures/${lectureId}/`);
        if (response.status === 403) throw new Error("Permission Denied");
        if (response.status !== 200) throw new Error(`Error! ${response.status}`);
        setlecture(response.data);
      } catch (err) {
        setError("Failed to fetch Lecture Details");
      } finally {
        setIsLoading(false);
      }
    };
    fetchLectureDetails();
  }, [lectureId]);

  const handleDeleteLecture = async () => {
    if (!window.confirm("Are you sure you want to delete this lecture? This action cannot be undone.")) {
      return;
    }

    setIsDeleting(true);
    try {
      // Backend par 'DELETE' method enable hona chahiye
      await apiClient.delete(`/lectures/${lectureId}/`);
      navigate(-1); // Success par pichle page par bhej dein
    } catch (err: any) {
      console.error("Failed to delete lecture:", err);
      const msg = err.response?.status === 405 
        ? "Error 405: Delete method not allowed on server. Please check backend view decorators."
        : "Failed to delete lecture.";
      alert(msg);
    } finally {
      setIsDeleting(false);
    }
  };

  if (isLoading) return <div className={styles.loader}>Loading...</div>;

  if (error || !lecture) {
    return <div className={styles.error}>{error || "Course not found"}</div>;
  }

  const isPending = lecture.validation_status === "pending";

  return (
    <div className={styles.pageWrapper}>
      <div className={styles.header}>
        <button onClick={() => navigate(-1)} className={styles.backBtn}>
          <ArrowLeft size={20} />
        </button>
        <div className={styles.titleInfo}>
          <h1>Review: {lecture.topic}</h1>
          <p>Course: <span>{lecture.content_source.course.title}</span></p>
        </div>
        <div className={styles.statusBadgeWrapper}>
           <span className={`${styles.statusBadge} ${styles[lecture.validation_status]}`}>
              {lecture.status_display}
           </span>
        </div>
      </div>

      <div className={styles.reviewGrid}>
        <div className={styles.contentColumn}>
          <div className={styles.sectionCard}>
            <div className={styles.sectionHeader}>
              <Video size={18} />
              <h2>Video Content</h2>
            </div>
            <div className={styles.videoBox}>
               <div className={styles.videoPlaceholder}>
                  <p>Video Preview (URL: {lecture.video_url || "N/A"})</p>
               </div>
            </div>
          </div>

          <div className={styles.sectionCard}>
            <div className={styles.sectionHeader}>
              <FileText size={18} />
              <h2>Summary & Transcription</h2>
            </div>
            <div className={styles.summaryContent}>
              <p>{lecture.summary_text}</p>
            </div>
          </div>
        </div>

        <div className={styles.actionColumn}>
          <div className={styles.metadataCard}>
            <div className={styles.metaHeader}>
               <Info size={16} /> <span>AI Metadata</span>
            </div>
            
            <div className={styles.metaGroup}>
              <label><Bot size={14} /> GENERATED BY</label>
              <p>SmartLearn AI Bot</p>
            </div>

            <div className={styles.metaGroup}>
              <label><Clock size={14} /> CREATED ON</label>
              <p>{new Date(lecture.created_at).toLocaleDateString()}</p>
            </div>

            <div className={styles.metaGroup}>
              <label><MessageSquare size={14} /> ORIGINAL PROMPT</label>
              <div className={styles.promptBox}>"{lecture.content_source.ai_prompt}"</div>
            </div>

            {lecture.rejection_comment && (
              <div className={styles.rejectionBox}>
                <label>REJECTION REASON</label>
                <p>{lecture.rejection_comment}</p>
              </div>
            )}
          </div>

          {isPending ? (
            <ValidationActionPanel lectureId={lecture.id} />
          ) : (
            <div className={styles.successNotice}>
              <div className={styles.successIcon}><CheckCircle size={24} /></div>
              <div className={styles.successText}>
                <h3>Validation Complete</h3>
                <p>This lecture is marked as <strong>Validated</strong>.</p>
              </div>
            </div>
          )}

          <button 
            className={styles.deleteLectureBtn} 
            onClick={handleDeleteLecture}
            disabled={isDeleting}
          >
            <Trash2 size={18} />
            {isDeleting ? "Deleting..." : "Delete Lecture"}
          </button>
        </div>
      </div>
    </div>
  );
};

export default LectureReviewPage;