import DashboardLayout from "@/Layout/DashboardLayout";
import type { LectureDetails } from "@/components/Dashboard/shared/Types";
import styles from "./LectureReviewPage.module.css";
import { useParams } from "react-router-dom";
import { useEffect, useState } from "react";
import apiClient from "@/api/apiClient";
import { useAuthStore } from "@/store/useAuthStore";
import ValidationActionPanel from "@/components/Dashboard/teacher/ValidationActionPanel";
const LectureReviewPage = () => {
  const role = useAuthStore((state) => state.role);
  const { id } = useParams<{ id: string }>();
  const lectureId = id;
  const [lecture, setlecture] = useState<LectureDetails | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!lectureId) return;
    const fetchLectureDetails = async () => {
      try {
        const response = await apiClient.get(`/lectures/${lectureId}/`);

        if (response.status === 403) {
          throw new Error("Permission Denied You do not Own this Course.");
        }

        if (response.status !== 200) {
          throw new Error(`Http Error! ${response.status}`);
        }

        const data: LectureDetails = response.data;
        console.log(data)
        setlecture(data);
      } catch (err) {
        console.error(`Failed to load lecture. Error: ${err}`);
        setError("Failed to fetch Lecture Details");
      } finally {
        setIsLoading(false);
      }
    };
    fetchLectureDetails();
  }, [lectureId]);

  if (isLoading) {
    return (
      <DashboardLayout userRole={role}>
        {" "}
        Lecture is Loading....{" "}
      </DashboardLayout>
    );
  }

  if (error) {
    return (
      <DashboardLayout userRole={role}>
        <h2 className={styles.error}>{error}</h2>
      </DashboardLayout>
    );
  }

  if (!lecture) {
    return (
      <DashboardLayout userRole={role}>Lecture Not Found.</DashboardLayout>
    );
  }

  const isPending = lecture.validation_status === "pending";
  return (
    <DashboardLayout userRole={role}>
      <h1 className={styles.pageTitle}>Review: {lecture.topic}</h1>
      <p className={styles.courseTitle}>
        Course: {lecture.content_source.course.title}
      </p>

      <div className={styles.reviewGrid}>
        {/* -------------------- LEFT COLUMN: Content Review -------------------- */}
        <div className={styles.contentColumn}>
          <h2>Video Content</h2>
          {/* Placeholder for the video player. In a real app, this would be an embedded iframe */}
          <div className={styles.videoPlayer}>
            <p>Video Player Placeholder (URL: {lecture.video_url || "N/A"})</p>
          </div>

          <h2>Summary Text</h2>
          <div className={styles.summaryBox}>
            <p>{lecture.summary_text}</p>
          </div>
        </div>

        {/* -------------------- RIGHT COLUMN: Actions & Metadata -------------------- */}
        <div className={styles.actionColumn}>
          <div className={styles.metadataBox}>
            <h3>Metadata</h3>
            <p>
              <strong>Generated By:</strong> AI Bot (
              {new Date(lecture.created_at).toLocaleDateString()})
            </p>
            <p>
              <strong>Status:</strong>{" "}
              <span className={styles.statusPill}>
                {lecture.status_display}
              </span>
            </p>
            <p>
              <strong>Original Prompt:</strong>
              <span className={styles.promptText}>
                {lecture.content_source.ai_prompt}
              </span>
            </p>
            {lecture.rejection_comment && (
              <p className={styles.rejectionComment}>
                <strong>Rejection Reason:</strong> {lecture.rejection_comment}
              </p>
            )}
          </div>

          {/* Validation/Rejection Panel (Only show if pending) */}
          {isPending && <ValidationActionPanel lectureId={lecture.id} />}

          {!isPending && (
            <div className={styles.validatedNotice}>
              <p>This lecture has already been **{lecture.status_display}**.</p>
            </div>
          )}
        </div>
      </div>
    </DashboardLayout>
  );
};

export default LectureReviewPage;
