# Generated by Django 5.2.8 on 2025-12-19 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_alter_lecture_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_file', models.FileField(upload_to='raw_content_uploads/%Y/%m/%d')),
                ('ai_prompt', models.TextField(help_text='the teachers help instructions for the AI Lecture generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_source',
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='content_source',
            field=models.ForeignKey(blank=True, help_text='the raw content source that generated this lecture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_lectures', to='lectures.contentsource'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=15)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.AddField(
            model_name='contentsource',
            name='course',
            field=models.ForeignKey(help_text='the cource this content is intended for', on_delete=django.db.models.deletion.CASCADE, related_name='content_sources', to='lectures.course'),
        ),
    ]
