# Generated by Django 5.2.8 on 2026-01-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='context',
            field=models.TextField(blank=True, help_text='Ai-Generated context for chatbot/Quiz/Assignment', null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='script',
            field=models.TextField(blank=True, help_text='Full Ai Generated Lecture Script', null=True),
        ),
    ]
