# Generated by Django 6.0.2 on 2026-03-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_lecture_context_lecture_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary Public ID for management', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_status',
            field=models.CharField(choices=[('none', 'None'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
