# Generated by Django 6.0.2 on 2026-03-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0008_course_thumbnail'),
        ('lectures', '0008_lecture_video_public_id_lecture_video_status_and_more'),
    ]

    operations = [
    ]
