# Generated by Django 6.0.2 on 2026-03-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_merge_20260314_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='review_progress',
            field=models.IntegerField(default=0, help_text="Teacher's review percentage of the generated lecture (0-100)"),
        ),
    ]
