# Generated by Django 6.0.2 on 2026-05-09 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0011_remove_lecture_review_progress_lectureprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.CharField(db_index=True, max_length=255)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_group_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_message',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_study_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_study_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_connection',
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
