# Generated by Django 6.0.2 on 2026-05-10 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0012_groupmessage_studyconnection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='room_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='groupmessage',
            table=None,
        ),
    ]
