# Generated by Django 6.0.2 on 2026-06-18 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0013_alter_groupmessage_room_id_alter_groupmessage_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='room_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_group_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='groupmessage',
            table='group_message',
        ),
    ]
