from rest_framework.permissions import IsAuthenticated
from users.permissions import IsTeacher
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from django.db.models import Count
from lectures.models import Lecture, Course
# Create your views here.


@api_view(["GET"])
@permission_classes([IsAuthenticated, IsTeacher])
def teacher_dashboard_metric(request):
    """
    Return Aggregated counts for the teacher dashboard (Total Courses, Pending Validations)
    only user with 'teacher' role should access this view
    """
    user = request.user

    total_courses = Course.objects.filter(teacher=user).count()

    # total lectures generated by current teachers uploaded content
    total_lectures = Lecture.objects.filter(
        generated_by=user
    ).count()
    pending_validation_count = Lecture.objects.filter(
        generated_by=user,
        validation_status='pending'
    ).count()
    total_validated_lectures = Lecture.objects.filter(
        validated_by=user
    ).count()
    return Response({
        "total_courses": total_courses,
        "total_lectures_generated": total_lectures,
        "pending_validation_count": pending_validation_count,
        "total_validated_lectures": total_validated_lectures
    })
