from django.shortcuts import get_object_or_404
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import status
from smartlearn_project.utils import get_letter_grade
from django.db.models import Avg, Count, Q, F
from django.contrib.auth import get_user_model
from django.apps import apps
from django.utils import timezone
from lectures.models import Lecture, Course, Enrollment, LectureProgress
from assessment.models import Assignment, Quiz, QuizSubmission, AssignmentSubmission

User = get_user_model()


@api_view(['GET'])
# IsTeacher permission agar hai toh add karein
@permission_classes([IsAuthenticated])
def teacher_dashboard_metric(request):
    """
    Original method for Teacher Dashboard.
    Reverted to original name to avoid import errors and master branch clashes.
    """
    user = request.user

    total_courses = Course.objects.filter(teacher=user).count()

    # Total lectures generated by current teacher
    total_lectures = Lecture.objects.filter(generated_by=user).count()

    pending_validation_count = Lecture.objects.filter(
        generated_by=user,
        validation_status='pending'
    ).count()

    total_validated_lectures = Lecture.objects.filter(
        generated_by=user,
        validation_status='validated'
    ).count()

    # Syllabus Coverage Logic (Percentage for the progress bar)
    # Calculation: (Validated / Total) * 100
    syllabus_coverage = 0
    if total_lectures > 0:
        syllabus_coverage = int(
            (total_validated_lectures / total_lectures) * 100)

    return Response({
        "total_courses": total_courses,
        "total_lectures_generated": total_lectures,
        "pending_validation_count": pending_validation_count,
        "total_validated_lectures": total_validated_lectures,
        "syllabus_coverage": syllabus_coverage,  # Frontend ki bar ke liye
    })


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def student_dashboard_metric(request):
    """
    New separate method for Student Dashboard metrics.
    Updated to fetch real progress from LectureProgress.
    """
    user = request.user

    # 1. Enrolled Courses count for current student
    courses = Course.objects.filter(enrollments__student=user)
    enrolled_courses_count = courses.count()

    # 2. Total Validated Lectures in those courses
    student_lectures = Lecture.objects.filter(
        content_source__course__in=courses,
        validation_status='validated'
    )
    total_lectures_count = student_lectures.count()

    # 3. Add Real Logic for Quizzes and Assignments
    total_quizzes = student_lectures.filter(
        quiz__isnull=False, quiz__status='published').count()

    total_assignments = student_lectures.filter(
        assignment__isnull=False, assignment__status='published').count()

    # 4. Dynamic Course Progress List for UI bars (Using actual LectureProgress)
    course_progress_list = []
    for course in courses:
        avg_progress = LectureProgress.objects.filter(
            user=user,
            lecture__content_source__course=course
        ).aggregate(avg=Avg('progress_percentage'))['avg'] or 0

        course_progress_list.append({
            "name": course.title,
            "progress": int(avg_progress)
        })

    return Response({
        "enrolled_courses": enrolled_courses_count,
        "completed_lectures": total_lectures_count,
        "completed_quizzes": total_quizzes,
        "pending_assignments": total_assignments,
        "full_name": getattr(user, 'full_name', user.username),
        "course_progress": course_progress_list,
        "message": "Student metrics fetched successfully"
    })


# ANALYTICS RELATED VIEWS

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def teacher_analytics(request):
    teacher = request.user

    # 1. Base counts & averages
    total_students = User.objects.filter(
        course_enrollments__course__teacher=teacher).distinct().count()

    quiz_subs = QuizSubmission.objects.filter(
        quiz__lecture__content_source__course__teacher=teacher)
    quiz_completed = quiz_subs.count()
    avg_grade_all = quiz_subs.aggregate(avg=Avg('score'))['avg'] or 0

    # Calculate real pass rate (assuming >= 50 is a pass)
    passed_quizzes = quiz_subs.filter(score__gte=50).count()
    pass_rate = round((passed_quizzes / quiz_completed * 100)
                      ) if quiz_completed > 0 else 0

    # 2. Submissions Aggregation (Assignments)
    asg_stats = AssignmentSubmission.objects.filter(
        assignment__lecture__content_source__course__teacher=teacher
    ).aggregate(
        total=Count('id'),
        pending=Count('id', filter=Q(score__isnull=True)),
        late=Count('id', filter=Q(submitted_at__gt=F('assignment__deadline')))
    )

    # Calculate real missed quizzes
    total_published_quizzes = Quiz.objects.filter(
        lecture__content_source__course__teacher=teacher, status='published').count()
    expected_quiz_subs = total_published_quizzes * total_students
    missed_quizzes = max(0, expected_quiz_subs - quiz_completed)

    # Calculate real Lecture validation states
    lecture_stats_db = Lecture.objects.filter(content_source__course__teacher=teacher).aggregate(
        total=Count('id'),
        pending=Count('id', filter=Q(validation_status='pending')),
        validated=Count('id', filter=Q(validation_status='validated'))
    )

    # 3. O(1) Course Mapping
    courses = teacher.taught_courses.annotate(
        student_count=Count('enrollments', distinct=True))

    course_scores = QuizSubmission.objects.filter(
        quiz__lecture__content_source__course__teacher=teacher
    ).values('quiz__lecture__content_source__course_id').annotate(avg_score=Avg('score'))

    score_dict = {item['quiz__lecture__content_source__course_id']: item['avg_score'] or 0 for item in course_scores}

    course_list = []
    for course in courses:
        score = score_dict.get(course.id, 0)
        course_list.append({
            "name": course.title,
            "students": course.student_count,
            "score": round(score, 1)
        })
    course_list = sorted(course_list, key=lambda x: x['score'], reverse=True)

    # 4. O(1) Student Progress Mapping
    student_ids = list(User.objects.filter(
        course_enrollments__course__teacher=teacher
    ).values_list('id', flat=True).distinct()[:5])

    students = User.objects.filter(id__in=student_ids)

    stu_scores = QuizSubmission.objects.filter(
        user_id__in=student_ids,
        quiz__lecture__content_source__course__teacher=teacher
    ).values('user_id').annotate(avg_score=Avg('score'))

    stu_score_dict = {item['user_id']: item['avg_score'] or 0 for item in stu_scores}

    student_progress = []
    colors = ['#6366f1', '#10b981', '#f59e0b', '#f43f5e', '#8b5cf6']

    for idx, student in enumerate(students):
        prog = stu_score_dict.get(student.id, 0)
        student_progress.append({
            "name": getattr(student, 'full_name', '') or student.email,
            "progress": round(prog, 1),
            "color": colors[idx % len(colors)],
            "avatar": f"https://i.pravatar.cc/150?u={student.id}"
        })

    # --- Formatting the Final Response ---
    stats = [
        {'label': 'AVG GRADE',
            'val': f"{round(avg_grade_all, 1)}%", 'color': '#6366f1'},
        {'label': 'PASS RATE', 'val': f"{pass_rate}%", 'color': '#10b981'},
        {'label': 'ACTIVE STUDENTS', 'val': str(
            total_students), 'color': '#f59e0b'},
        {'label': 'COURSES', 'val': str(courses.count()), 'color': '#f43f5e'},
    ]

    lecture_stats_list = [
        {'name': 'Total',
            'value': lecture_stats_db['total'] or 0, 'color': '#f59e0b'},
        {'name': 'Generated', 'value': Quiz.objects.filter(
            lecture__content_source__course__teacher=teacher).count(), 'color': '#6366f1'},
        {'name': 'Pending',
            'value': lecture_stats_db['pending'] or 0, 'color': '#f43f5e'},
        {'name': 'Validated',
            'value': lecture_stats_db['validated'] or 0, 'color': '#10b981'},
    ]

    asg_total = asg_stats['total'] or 0
    asg_late = asg_stats['late'] or 0
    asg_pending = asg_stats['pending'] or 0

    submissions = {
        "assignment": {
            "onTime": asg_total - asg_late,
            "late": asg_late,
            "pending": asg_pending
        },
        "quiz": {
            "completed": quiz_completed,
            "missed": missed_quizzes,
            "avgGrade": f"{round(avg_grade_all, 1)}%"
        },
        "project": {"submitted": 0, "inProgress": 0, "graded": 0}
    }

    return Response({
        "stats": stats,
        "lectureProgress": lecture_stats_list,
        "submissions": submissions,
        "courses": course_list,
        "studentProgress": student_progress,
        "passPercentage": pass_rate
    })


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def student_analytics(request):
    user = request.user

    # 1. Overall Quick Stats
    avg_quiz = QuizSubmission.objects.filter(
        user=user).aggregate(avg=Avg('score'))['avg'] or 0

    total_asg_count = Assignment.objects.filter(
        lecture__content_source__course__enrollments__student=user, status='published'
    ).count()

    completed_asg = AssignmentSubmission.objects.filter(
        user=user, score__isnull=False
    ).count()

    completion_rate = round(
        (completed_asg / total_asg_count * 100), 1) if total_asg_count > 0 else 0

    # 2. Course Progress & Quiz Averages
    enrolled_courses = Enrollment.objects.filter(
        student=user).select_related('course') if Enrollment else []

    course_quiz_avgs = QuizSubmission.objects.filter(
        user=user
    ).values('quiz__lecture__content_source__course_id').annotate(avg_score=Avg('score'))

    quiz_avg_dict = {item['quiz__lecture__content_source__course_id']: item['avg_score'] or 0 for item in course_quiz_avgs}

    courses_data = []
    for enrollment in enrolled_courses:
        course = enrollment.course
        course_quiz_avg = quiz_avg_dict.get(course.id, 0)

        # GET DETAILED LECTURE PROGRESS (For the Line/Area Chart)
        # We fetch all lectures for this course and the user's progress for each
        lecture_progress_records = LectureProgress.objects.filter(
            user=user,
            lecture__content_source__course=course
        ).select_related('lecture').order_by('last_watched')

        # REAL WATCH PROGRESS from LectureProgress
        watch_progress = LectureProgress.objects.filter(
            user=user,
            lecture__content_source__course=course
        ).aggregate(avg_prog=Avg('progress_percentage'))['avg_prog'] or 0

        graph_points = []
        for lp in lecture_progress_records:
            graph_points.append({
                "id": lp.lecture.id,
                "title": lp.lecture.topic,
                "progress": lp.progress_percentage,
                "date": lp.last_watched.strftime("%b %d")  # e.g., "Jan 06"
            })

        courses_data.append({
            "id": course.id,
            "name": course.title,
            "watch": int(watch_progress),
            "quiz": round(course_quiz_avg, 1),
            "lectures": graph_points
        })

# 3. Active Assignments (Existing logic kept)
    all_asg = Assignment.objects.filter(
        lecture__content_source__course__enrollments__student=user, status='published'
    ).order_by('-deadline')[:3]

    sub_dict = {sub.assignment_id: sub for sub in AssignmentSubmission.objects.filter(
        user=user, assignment_id__in=[asg.id for asg in all_asg])}

    active_assignments = []
    for asg in all_asg:
        sub = sub_dict.get(asg.id)
        deadline_label = "Submitted" if sub else (asg.deadline.strftime(
            "%d %b") if asg.deadline and timezone.now() <= asg.deadline else "Overdue" if asg.deadline else "Active")

        active_assignments.append({
            "title": asg.assignment_data.get('title', 'Assignment') if isinstance(asg.assignment_data, dict) else "Assignment",
            "deadline": deadline_label,
            "progress": 100 if sub else 0
        })

    # 4. Recent Quiz Performance (Existing logic kept)
    recent_quizzes = QuizSubmission.objects.filter(
        user=user).select_related('quiz__lecture').order_by('-id')[:5]
    quiz_perf_data = [{"name": q.quiz.lecture.topic if q.quiz.lecture else "Quiz", "quiz": float(
        q.score)} for q in recent_quizzes]

    return Response({
        "stats": {
            "completion": completion_rate,
            "completion_trend": "+2%",
            "avg_quiz": round(avg_quiz, 1),
            "quiz_trend": "+5%",
            "study_hours": 12,
            "hours_trend": "+2h",
            "grade": get_letter_grade(avg_quiz)
        },
        "courses": courses_data,
        "quizzes_performance": quiz_perf_data,
        "assignments": active_assignments,
        "recommendations": [
            f"Review topics in {courses_data[0]['name']}" if courses_data else "Review your weak areas",
            "Complete pending quizzes to improve GPA",
            "Keep an eye on upcoming assignment deadlines"
        ]
    })


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def teacher_gradebook_summary(request, course_id):
    teacher = request.user
    student_query = User.objects.filter(
        course_enrollments__course__teacher=teacher)
    if course_id:
        student_query = student_query.filter(
            course_enrollments__course_id=course_id)
    students = student_query.distinct()

    asg_filter = {
        'assignment__lecture__content_source__course__teacher': teacher, 'score__isnull': False}
    if course_id:
        asg_filter['assignment__lecture__content_source__course_id'] = course_id

    asg_avgs = AssignmentSubmission.objects.filter(
        **asg_filter).values('user_id').annotate(avg_score=Avg('score'))
    asg_dict = {item['user_id']: item['avg_score'] or 0 for item in asg_avgs}

    quiz_filter = {'quiz__lecture__content_source__course__teacher': teacher}
    if course_id:
        quiz_filter['quiz__lecture__content_source__course_id'] = course_id

    quiz_avgs = QuizSubmission.objects.filter(
        **quiz_filter).values('user_id').annotate(avg_score=Avg('score'))
    quiz_dict = {item['user_id']: item['avg_score'] or 0 for item in quiz_avgs}

    gradebook_data = []
    for student in students:
        asg_avg = asg_dict.get(student.id, 0)
        quiz_avg = quiz_dict.get(student.id, 0)
        total_score = round((asg_avg + quiz_avg), 2)

        gradebook_data.append({
            "id": student.id,
            "student_name": getattr(student, 'full_name', student.email) or student.email,
            "student_id_num": f"STU-{student.id:03d}",
            "avatar_url": f"https://i.pravatar.cc/150?u={student.id}",
            "assignments_marks": round(asg_avg, 2),
            "quizzes_marks": round(quiz_avg, 2),
            "exam_marks": 0,
            "score": total_score,
            "grade": get_letter_grade(total_score),
            "total_possible": 100
        })

    return Response(gradebook_data)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def student_gradebook_summary(request):
    user = request.user

    quiz_data = QuizSubmission.objects.filter(
        user=user, score__isnull=False
    ).annotate(
        course_id=F('quiz__lecture__content_source__course__id'),
        course_title=F('quiz__lecture__content_source__course__title'),
        teacher_name=F(
            'quiz__lecture__content_source__course__teacher__full_name'),
        teacher_user=F('quiz__lecture__content_source__course__teacher__email')
    ).values('course_id', 'course_title', 'teacher_name', 'teacher_user').annotate(avg_score=Avg('score'))

    asg_data = AssignmentSubmission.objects.filter(
        user=user, score__isnull=False
    ).annotate(
        course_id=F('assignment__lecture__content_source__course__id'),
        course_title=F('assignment__lecture__content_source__course__title'),
        teacher_name=F(
            'assignment__lecture__content_source__course__teacher__full_name'),
        teacher_user=F(
            'assignment__lecture__content_source__course__teacher__email')
    ).values('course_id', 'course_title', 'teacher_name', 'teacher_user').annotate(avg_score=Avg('score'))

    courses_dict = {}
    for q in quiz_data:
        courses_dict[q['course_id']] = {"course": q['course_title'], "instructor": q['teacher_name'] or q['teacher_user'],
                                        "quizzes_marks": q['avg_score'] or 0, "assignments_marks": 0, "exam_marks": 0, "status": "Completed"}

    for a in asg_data:
        c_id = a['course_id']
        if c_id not in courses_dict:
            courses_dict[c_id] = {"course": a['course_title'], "instructor": a['teacher_name'] or a['teacher_user'],
                                  "quizzes_marks": 0, "assignments_marks": 0, "exam_marks": 0, "status": "Completed"}
        courses_dict[c_id]['assignments_marks'] = a['avg_score'] or 0

    final_course_list = []
    total_avg_sum = 0
    for c_id, data in courses_dict.items():
        total_score = round(
            (data["assignments_marks"] + data["quizzes_marks"]), 2)
        total_avg_sum += total_score
        data.update({"score": total_score, "grade": get_letter_grade(total_score), "assignments_marks": round(
            data["assignments_marks"], 2), "quizzes_marks": round(data["quizzes_marks"], 2)})
        final_course_list.append(data)

    course_count = len(final_course_list)
    return Response({
        "stats": {
            "gpa": round((total_avg_sum / (course_count * 25)), 2) if course_count > 0 else 0.00,
            "total_courses": course_count,
            "completed_courses": course_count,
            "quizzes_done": QuizSubmission.objects.filter(user=user).count(),
            "assignments_done": AssignmentSubmission.objects.filter(user=user).count()
        },
        "courses": final_course_list
    })


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def student_detail_report(request, student_id):
    teacher = request.user
    student = get_object_or_404(User, id=student_id)
    course_id = request.query_params.get('course_id')

    asg_filter = {'user': student,
                  'assignment__lecture__content_source__course__teacher': teacher}
    quiz_filter = {'user': student,
                   'quiz__lecture__content_source__course__teacher': teacher}

    if course_id:
        asg_filter['assignment__lecture__content_source__course_id'] = course_id
        quiz_filter['quiz__lecture__content_source__course_id'] = course_id

    assignments = AssignmentSubmission.objects.filter(
        **asg_filter).select_related('assignment__lecture')
    asg_list = [{"title": sub.assignment.lecture.topic if (sub.assignment and sub.assignment.lecture) else "Assignment", "score": sub.score or 0,
                 "feedback": sub.feedback or "No feedback yet", "status": "Graded" if sub.score is not None else "Submitted"} for sub in assignments]

    quizzes = QuizSubmission.objects.filter(
        **quiz_filter).select_related('quiz__lecture')
    quiz_list = [{"title": sub.quiz.lecture.topic if (
        sub.quiz and sub.quiz.lecture) else "Quiz", "score": sub.score or 0, "submitted_at": sub.submitted_at} for sub in quizzes]

    course_info = None
    if course_id:
        # CourseModel = apps.get_model('courses', 'Course')
        c_obj = Course.objects.filter(
            id=course_id, teacher=teacher).first()
        if c_obj:
            course_info = {"id": c_obj.id, "title": c_obj.title}

    return Response({
        "student_info": {"name": getattr(student, 'full_name', student.email) or student.email, "email": student.email, "id_num": f"STU-{student.id:03d}", "id": student.id},
        "course_info": course_info,
        "assignments": asg_list,
        "quizzes": quiz_list
    }, status=status.HTTP_200_OK)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_student_video_detail(request, student_id, course_id):
    teacher = request.user

    if not course_id:
        return Response({"error": "course_id is required"}, status=400)

    # Ensure the course belongs to this teacher
    course = get_object_or_404(Course, id=course_id, teacher=teacher)

    # Ensure the student exists
    student = get_object_or_404(User, id=student_id)

    # Get all lectures for this course
    lectures = Lecture.objects.filter(
        content_source__course=course).order_by('id')

    # Get the student's progress for these lectures
    progress_map = {
        lp.lecture_id: lp
        for lp in LectureProgress.objects.filter(user=student, lecture__in=lectures)
    }

    video_details = []
    for lecture in lectures:
        progress_obj = progress_map.get(lecture.id)

        video_details.append({
            "lecture_id": lecture.id,
            "title": lecture.topic,
            "progress": progress_obj.progress_percentage if progress_obj else 0,
            "last_watched": progress_obj.last_watched.strftime("%B %d, %Y") if progress_obj and progress_obj.last_watched else "Not started",
            "status": "Completed" if progress_obj and progress_obj.progress_percentage >= 95 else "In Progress" if progress_obj and progress_obj.progress_percentage > 0 else "Not Started"
        })

    # Overall course watch percentage for this student
    total_watch = sum(item['progress'] for item in video_details) / \
        len(video_details) if video_details else 0

    return Response({
        "student_name": getattr(student, 'full_name', student.email),
        "course_name": course.title,
        "overall_watch": round(total_watch, 1),
        "lectures": video_details
    })


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_course_students(request, course_id):
    # Fetch all students enrolled in the specific course
    enrollments = Enrollment.objects.filter(
        course_id=course_id).select_related('student')

    student_data = []
    for enrollment in enrollments:
        student = enrollment.student
        # Calculate average video progress for this student in this specific course
        avg_progress = LectureProgress.objects.filter(
            user=student,
            lecture__content_source__course_id=course_id
        ).aggregate(Avg('progress_percentage'))['progress_percentage__avg'] or 0

        student_data.append({
            "id": student.id,
            "full_name": student.get_full_name() or student.email,
            "email": student.email,
            "video_progress": round(avg_progress, 1)
        })

    return Response(student_data)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_teacher_courses(request):
    # Fetch courses owned by the logged-in teacher
    courses = Course.objects.filter(teacher=request.user)
    data = [{"id": c.id, "title": c.title} for c in courses]
    return Response(data)
